version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  jobs:
    image: contribsys/faktory:latest
    command: ./faktory -b :7419 -w :7420 -l debug
    env_file:
      - .env
    ports:
      - '7419:7419'
      - '7420:7420'
  websocket-kv:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_WS_PASSWORD
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - websocket-kv:/data
    env_file:
      - .env

# create local volume for postgres data to persist through computer restarts
volumes:
  postgres-data:
    driver: local
  websocket-kv:
    driver: local
