version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

# create local volume for postgres data to persist through computer restarts
volumes:
  postgres-data:
    driver: local
