version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  jobs:
    image: contribsys/faktory:latest
    command: ./faktory -b :7419 -w :7420 -l debug
    env_file:
      - .env
    ports:
      - '7419:7419'
      - '7420:7420'

# create local volume for postgres data to persist through computer restarts
volumes:
  postgres-data:
    driver: local
