services:
  # A Node web service
  - type: web
    name: startup-web
    plan: starter
    runtime: node
    repo: https://github.com/sammynave/startup.git
    healthCheckPath: /200
    buildCommand: pnpm build:render
    startCommand: node build/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: startup-db
          property: connectionString
      - key: PUBLIC_FAKTORY_URL
        fromService:
          type: web
          name: startup-faktory
          property: host
      - key: FAKTORY_URL
        fromService:
          type: web
          name: startup-faktory
          property: host

  - type: web
    name: startup-worker
    plan: starter
    runtime: node
    repo: https://github.com/sammynave/startup.git
    buildCommand: pnpm build:render
    startCommand: node build/index.js
    envVars:
      - key: WORKER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: startup-db
          property: connectionString
      - key: PUBLIC_FAKTORY_URL
        fromService:
          type: web
          name: startup-faktory
          property: host
      - key: FAKTORY_URL
        fromService:
          type: web
          name: startup-faktory
          property: host

  - type: web
    name: startup-faktory
    plan: starter
    runtime: docker
    # url: docker.io/contribsys/faktory:latest
    repo: https://github.com/contribsys/faktory-render
    envVars:
      - fromGroup: startup-env

databases:
  - name: startup-db
    plan: free
