services:
  # A Node web service
  - type: web
    name: startup-web
    plan: free
    runtime: node
    repo: https://github.com/sammynave/startup.git
    healthCheckPath: /200
    buildCommand: pnpm build:render
    startCommand: node build/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: startup-db
          property: connectionString
      - fromGroup: startup-env

databases:
  - name: startup-db
    plan: free
